#!/bin/bash -l
#SBATCH -p test    # the name of the pool
##SBATCH --constraint=cputype
#SBATCH --nodes 1         
#SBATCH --ntasks-per-node=16 # Tasks per node
#SBATCH --ntasks 16      # total number of cores (processes)
#SBATCH -t 00:02:00        # time as hh:mm:ss
#SBATCH -J title     
#SBATCH -e jobfile.err%J
#SBATCH -o jobfile.out%J
#SBATCH --mem-per-cpu=100
#SBATCH --workdir=/wrk/group/compchem/
#SBATCH --mail-type=END
#SBATCH --mail-user=your-email           

